"""The two .env secrets of an installed plugin service: generated by the real
scripts/init_secrets.py in a subprocess, only when missing (idempotent),
restored rather than regenerated after a remove that kept them, deleted on
purge, and never returned, printed or logged."""

import base64
import os
import stat
import subprocess

import pytest

from aab_installer import envfile


def values(env) -> dict[str, str]:
    out = {}
    for line in env.read_text(encoding="utf-8").splitlines():
        if line and not line.startswith("#"):
            k, _, v = line.partition("=")
            out[k] = v
    return out


def no_runner(argv):
    raise AssertionError(f"init_secrets must not run: {argv}")


def test_ensure_generates_both_secrets_once(project, capsys):
    env = project / ".env"
    before = env.read_bytes()
    added = envfile.ensure(project, "finance")
    assert added == ["PLUGIN_TOKEN_FINANCE", "PLUGIN_SECRETS_KEY_FINANCE"]
    v = values(env)
    assert len(bytes.fromhex(v["PLUGIN_TOKEN_FINANCE"])) == 32
    assert len(base64.urlsafe_b64decode(v["PLUGIN_SECRETS_KEY_FINANCE"])) == 32
    assert env.read_bytes().startswith(before)          # appended; nothing else touched
    text = env.read_text(encoding="utf-8")
    assert "# Broker <-> plugin-finance token" in text
    assert "# Fernet key for plugin-finance's own secret volume" in text
    # Idempotent: a second run changes nothing and runs nothing.
    after = env.read_bytes()
    assert envfile.ensure(project, "finance", runner=no_runner) == []
    assert env.read_bytes() == after
    out = capsys.readouterr()
    for secret in (v["PLUGIN_TOKEN_FINANCE"], v["PLUGIN_SECRETS_KEY_FINANCE"]):
        assert secret not in out.out and secret not in out.err


def test_ensure_fills_an_empty_line(project):
    env = project / ".env"
    env.write_bytes(env.read_bytes() + b"PLUGIN_TOKEN_FINANCE=\n")
    envfile.ensure(project, "finance")
    lines = [l for l in env.read_text(encoding="utf-8").splitlines()
             if l.startswith("PLUGIN_TOKEN_FINANCE=")]
    assert len(lines) == 1 and len(lines[0]) > len("PLUGIN_TOKEN_FINANCE=") + 32


def test_ensure_leaves_other_services_alone(project):
    envfile.ensure(project, "finance")
    before = values(project / ".env")
    envfile.ensure(project, "budget")
    after = values(project / ".env")
    assert {k: after[k] for k in before} == before
    assert after["PLUGIN_TOKEN_BUDGET"] != after["PLUGIN_TOKEN_FINANCE"]


def test_ensure_passes_the_right_argv(project):
    seen = []

    def runner(argv):
        seen.append(list(argv))
        name = argv[-1]
        with open(project / ".env", "ab") as f:
            f.write(f"{name}=x\n".encode())
        return subprocess.CompletedProcess(argv, 0, "", "")

    assert envfile.ensure(project, "finance", runner=runner, python="py") == [
        "PLUGIN_TOKEN_FINANCE", "PLUGIN_SECRETS_KEY_FINANCE"]
    script = str(project / "scripts" / "init_secrets.py")
    env = str(project / ".env")
    assert seen == [["py", script, "--out", env, "--rotate", "PLUGIN_TOKEN_FINANCE"],
                    ["py", script, "--out", env, "--rotate", "PLUGIN_SECRETS_KEY_FINANCE"]]


def test_a_failing_generator_is_an_error_without_its_output(project):
    def runner(argv):
        return subprocess.CompletedProcess(argv, 1, "SECRET-ish stdout", "SECRET-ish stderr")
    with pytest.raises(RuntimeError) as e:
        envfile.ensure(project, "finance", runner=runner)
    assert "exit 1" in str(e.value) and "SECRET" not in str(e.value)


def test_a_generator_that_writes_nothing_is_an_error(project):
    with pytest.raises(RuntimeError, match="did not write"):
        envfile.ensure(project, "finance",
                       runner=lambda argv: subprocess.CompletedProcess(argv, 0, "", ""))


def test_ensure_needs_an_existing_env(tmp_path):
    with pytest.raises(RuntimeError, match="does not exist"):
        envfile.ensure(tmp_path, "finance", runner=no_runner)


@pytest.mark.parametrize("service", ["", "Finance", "fin_ance", "a", "../x", "x" * 40])
def test_invalid_service_names_are_refused(project, service):
    with pytest.raises(ValueError):
        envfile.ensure(project, service, runner=no_runner)


def test_retire_keeps_the_values_and_ensure_restores_them(project):
    env = project / ".env"
    envfile.ensure(project, "finance")
    kept = values(env)
    assert envfile.retire(env, "finance") == ["PLUGIN_SECRETS_KEY_FINANCE",
                                              "PLUGIN_TOKEN_FINANCE"]
    assert not envfile.has_value(env, "PLUGIN_TOKEN_FINANCE")
    assert "PLUGIN_TOKEN_FINANCE" not in values(env)    # commented out
    # Reinstall: the same values come back, so the kept volume still decrypts.
    assert envfile.ensure(project, "finance", runner=no_runner) == [
        "PLUGIN_TOKEN_FINANCE", "PLUGIN_SECRETS_KEY_FINANCE"]
    restored = values(env)
    assert restored["PLUGIN_TOKEN_FINANCE"] == kept["PLUGIN_TOKEN_FINANCE"]
    assert restored["PLUGIN_SECRETS_KEY_FINANCE"] == kept["PLUGIN_SECRETS_KEY_FINANCE"]


def test_purge_deletes_active_and_retired_lines_and_their_comments(project):
    env = project / ".env"
    before = env.read_bytes()
    envfile.ensure(project, "finance")
    envfile.ensure(project, "financex")                 # a name sharing the prefix
    envfile.retire(env, "finance")
    assert envfile.purge(env, "finance") == ["PLUGIN_SECRETS_KEY_FINANCE",
                                             "PLUGIN_TOKEN_FINANCE"]
    text = env.read_text(encoding="utf-8")
    assert "PLUGIN_TOKEN_FINANCE=" not in text and "plugin-finance " not in text
    assert "plugin-finance'" not in text
    assert envfile.has_value(env, "PLUGIN_TOKEN_FINANCEX")
    assert "# Broker <-> plugin-financex token" in text
    assert env.read_bytes().startswith(before)
    assert envfile.purge(env, "finance") == []


def test_rewrites_keep_the_files_owner(project, monkeypatch):
    """The installer is root; the host's .env must stay the deploying user's."""
    env = project / ".env"
    envfile.ensure(project, "finance")
    st = os.stat(env)
    calls = []
    monkeypatch.setattr(os, "chown", lambda path, uid, gid: calls.append((uid, gid)),
                        raising=False)
    envfile.retire(env, "finance")                       # one rewrite
    envfile.ensure(project, "finance", runner=no_runner)  # one per restored name
    envfile.purge(env, "finance")                        # one rewrite
    assert calls == [(st.st_uid, st.st_gid)] * 4


@pytest.mark.skipif(os.name != "posix", reason="POSIX file modes")
def test_rewrites_keep_mode_0600(project):
    env = project / ".env"
    envfile.ensure(project, "finance")
    envfile.retire(env, "finance")
    assert stat.S_IMODE(os.stat(env).st_mode) == 0o600
    envfile.ensure(project, "finance", runner=no_runner)
    assert stat.S_IMODE(os.stat(env).st_mode) == 0o600
    envfile.purge(env, "finance")
    assert stat.S_IMODE(os.stat(env).st_mode) == 0o600
