"""The two .env secrets an installed plugin service needs, managed without ever printing them.

Each external plugin service gets its own `PLUGIN_TOKEN_<SVC>` (the broker
presents it as X-Plugin-Token) and `PLUGIN_SECRETS_KEY_<SVC>` (the Fernet key
of its own secret volume), exactly like the in-tree services. They are
generated by `scripts/init_secrets.py --rotate NAME` in a subprocess, the one
tool that writes deployment secrets: the right shape, a 0600 file, and
nothing secret on stdout. This module decides WHETHER a name needs
generating, and never logs or prints a value.

  ensure(root, service)   idempotent: generates only the names missing (or
                          empty), and restores a name a previous remove
                          retired instead of minting a new one, so a
                          reinstall can still decrypt the kept secret volume.
  retire(env, service)    on remove without purge: comment both lines out
                          (`#aab-retired# NAME=...`), value kept.
  purge(env, service)     on remove with purge: delete both lines, active or
                          retired.
  plugin_token(env, svc)  the one value read out: the service's active
                          PLUGIN_TOKEN_<SVC>, for `GET /services` only. The
                          broker already holds every plugin token (it is the
                          caller each token authenticates); this hands it a
                          new service's token without recreating the broker
                          to change its environment. Never the secrets key.
  plugin_tokens(env)      every active PLUGIN_TOKEN_* value, so a job's log
                          lines can mask them whatever their shape.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
import tempfile
from collections.abc import Callable, Sequence
from pathlib import Path

from .descriptor import SERVICE_RE

RETIRED = b"#aab-retired# "
INIT_SECRETS = Path("scripts") / "init_secrets.py"

# (argv) -> CompletedProcess; injectable so tests need no interpreter games.
Runner = Callable[[Sequence[str]], subprocess.CompletedProcess]


def secret_names(service: str) -> tuple[str, str]:
    if not SERVICE_RE.match(service or ""):
        raise ValueError(f"service {service!r} must match {SERVICE_RE.pattern}")
    upper = service.upper()
    return f"PLUGIN_TOKEN_{upper}", f"PLUGIN_SECRETS_KEY_{upper}"


def _lines(env: Path) -> list[bytes]:
    return env.read_bytes().splitlines(keepends=True) if env.exists() else []


def has_value(env: Path, name: str) -> bool:
    """Is `name=<something>` set (uncommented, non-empty) in `env`?"""
    prefix = f"{name}=".encode("ascii")
    return any(line.startswith(prefix) and line[len(prefix):].strip() for line in _lines(env))


def _unquote(value: bytes) -> bytes:
    value = value.strip()
    # Compose strips one pair of matching quotes; init_secrets writes none.
    if len(value) >= 2 and value[:1] in (b'"', b"'") and value[-1:] == value[:1]:
        value = value[1:-1]
    return value


def _active(env: Path, prefix: bytes) -> dict[str, bytes]:
    """{name: value} of every uncommented `NAME=value` line whose name starts
    with `prefix`; the last assignment wins, as in compose."""
    out: dict[str, bytes] = {}
    for line in _lines(env):
        if not line.startswith(prefix):
            continue
        name, sep, value = line.partition(b"=")
        if sep and name.strip() == name:
            out[name.decode("ascii", "replace")] = _unquote(value)
    return out


def plugin_token(env: Path, service: str) -> str | None:
    """The active PLUGIN_TOKEN_<SERVICE> value, or None when it is missing,
    empty, retired or not printable ASCII. For `GET /services` only: the
    caller returns it to the broker and never logs it."""
    name, _ = secret_names(service)
    raw = _active(env, f"{name}=".encode("ascii")).get(name, b"")
    try:
        token = raw.decode("ascii")
    except UnicodeDecodeError:
        return None
    return token if token and token.isprintable() and not any(c.isspace() for c in token) \
        else None


def plugin_tokens(env: Path) -> tuple[str, ...]:
    """Every active PLUGIN_TOKEN_* value (for masking job log lines)."""
    out = []
    for value in _active(env, b"PLUGIN_TOKEN_").values():
        text = value.decode("utf-8", "replace")
        if text:
            out.append(text)
    return tuple(out)


def _write_private(path: Path, data: bytes) -> None:
    """Atomic replace with mode 0600, keeping the file's owner, like
    scripts/init_secrets.py: the installer is root, and the host's .env must
    stay readable by the user who deploys."""
    st = os.stat(path)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".env.tmp-")
    try:
        with os.fdopen(fd, "wb") as f:
            f.write(data)
        os.chmod(tmp, 0o600)
        if hasattr(os, "chown"):
            try:
                os.chown(tmp, st.st_uid, st.st_gid)
            except PermissionError:
                pass            # an unprivileged writer can only own the file itself
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def _default_runner(argv: Sequence[str]) -> subprocess.CompletedProcess:
    # Output is captured and dropped by the caller except for its exit code:
    # init_secrets prints only names and hints, but nothing here relays it.
    return subprocess.run(list(argv), capture_output=True, text=True, timeout=60)


def _restore(env: Path, name: str) -> bool:
    """Uncomment a retired `name=` line. Returns whether one was restored."""
    lines = _lines(env)
    prefix = RETIRED + f"{name}=".encode("ascii")
    hits = [i for i, line in enumerate(lines) if line.startswith(prefix)]
    if len(hits) != 1:
        return False
    i = hits[0]
    lines[i] = lines[i][len(RETIRED):]
    # Drop an empty active `name=` line init_secrets would otherwise keep.
    empty = [j for j, line in enumerate(lines)
             if j != i and line.rstrip(b"\r\n") == f"{name}=".encode("ascii")]
    for j in reversed(empty):
        del lines[j]
    _write_private(env, b"".join(lines))
    return True


def ensure(root: Path, service: str, runner: Runner | None = None,
           python: str | None = None) -> list[str]:
    """Make sure `root/.env` holds both secrets for `service`. Returns the
    names that were added (generated or restored); empty when nothing was
    missing. Raises RuntimeError when the generator fails."""
    root = Path(root)
    env = root / ".env"
    if not env.exists():
        raise RuntimeError(f"{env} does not exist; run scripts/init_secrets.py first")
    run = runner or _default_runner
    added = []
    for name in secret_names(service):
        if has_value(env, name):
            continue
        if not _restore(env, name):
            argv = [python or sys.executable, str(root / INIT_SECRETS), "--out", str(env),
                    "--rotate", name]
            result = run(argv)
            if result.returncode != 0:
                # The exit code only: never relay the subprocess's output.
                raise RuntimeError(f"init_secrets.py --rotate {name} failed "
                                   f"(exit {result.returncode})")
            if not has_value(env, name):
                raise RuntimeError(f"init_secrets.py --rotate {name} did not write it")
        added.append(name)
    return added


def retire(env: Path, service: str) -> list[str]:
    """Comment out both secrets (value kept). Returns the names retired."""
    names = secret_names(service)
    lines = _lines(env)
    done = []
    for i, line in enumerate(lines):
        for name in names:
            if line.startswith(f"{name}=".encode("ascii")):
                lines[i] = RETIRED + line
                done.append(name)
    if done:
        _write_private(env, b"".join(lines))
    return sorted(set(done))


def purge(env: Path, service: str) -> list[str]:
    """Delete both secrets, active or retired. Returns the names removed."""
    names = secret_names(service)
    active = [f"{n}=".encode("ascii") for n in names]
    prefixes = active + [RETIRED + p for p in active]
    # init_secrets writes a comment naming plugin-<service> above an appended
    # entry; it goes with the entry (not plugin-<service>xyz's).
    mentions = re.compile(rb"plugin-" + service.encode("ascii") + rb"(?![a-z0-9])")
    keep, done = [], set()
    for line in _lines(env):
        hit = next((p for p in prefixes if line.startswith(p)), None)
        if hit is None:
            keep.append(line)
            continue
        done.add(hit.removeprefix(RETIRED).decode("ascii").rstrip("="))
        if keep and keep[-1].startswith(b"# ") and mentions.search(keep[-1]):
            keep.pop()
    if done:
        _write_private(env, b"".join(keep))
    return sorted(done)
