"""Broker configuration, environment-first (12-factor: everything via env vars).

Only broker-wide settings live here. Per-plugin settings (sidecar URL, GitHub
App id, ...) are plugin config stored in the database and edited from the
console, so adding a plugin never touches this file.
"""

import os
from functools import lru_cache

from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    # The broker's own database: principals, keys, grants, decisions, ledger.
    broker_db: str = "/gwdata/broker.db"

    # Host headers accepted on the /mcp endpoint (DNS-rebinding protection).
    # Comma-separated; ":*" allows any port. Extend when serving beyond localhost.
    mcp_allowed_hosts: str = "localhost:*,127.0.0.1:*"

    # --- Broker-owned secrets (generated by scripts/init_secrets.py) --------

    # One-time token that authorizes creating the owner account. Inert once
    # setup has completed (app_config.setup_completed), even if left in .env.
    setup_token: str | None = None
    # Fernet key encrypting plugin_secrets at rest (used only via crypto.py).
    broker_secrets_key: str | None = None
    # HMAC key for the hash-chained decision record.
    decision_signing_key: str | None = None

    # --- Owner sessions ------------------------------------------------------

    # Console login sessions die after this much inactivity (12h) or this long
    # after login regardless of activity (7d), whichever comes first.
    session_idle_seconds: int = 43200
    session_absolute_seconds: int = 604800

    # --- Authority -----------------------------------------------------------

    # How many delegation hops below a root key are allowed. Each hop can only
    # narrow, but deep chains are hard for a human to reason about.
    max_delegation_depth: int = 3
    # How many live child keys one key may have delegated at once. Delegation
    # needs no human, so this (with the depth limit) keeps any tree bounded.
    max_live_delegations: int = 25

    # How often the scheduler looks for due queued actions.
    scheduler_tick_seconds: int = 15

    # --- Engine ----------------------------------------------------------------

    # Plugin API calls give up after this long. A timeout after the request
    # was sent is an unknown outcome (502), never retried automatically.
    plugin_timeout_seconds: float = 30.0
    # How long folder ancestry answers (subtree narrowing) are cached.
    ancestors_cache_seconds: int = 60
    # Scheduling bounds for run_at / delay_seconds (ported from WA_GW).
    schedule_min_lead_seconds: int = 30
    schedule_max_horizon_days: int = 30
    # Drafts nobody decides on expire after this long.
    draft_ttl_hours: int = 24
    # Longest expansion a permission request may ask for.
    grant_max_hours: int = 24 * 30
    # Long-poll bounds for `long_poll` actions over REST (?wait=).
    long_poll_max_wait_seconds: int = 60
    long_poll_interval_seconds: float = 1.0

    # --- Internet exposure (see deploy/DEPLOY.md) ---------------------------

    # Origin lockdown. When origin_secret is set, EVERY request must carry it in
    # origin_secret_header (injected by a Cloudflare Transform Rule), else 403.
    # This stops anyone who finds the origin IP from bypassing Cloudflare.
    origin_secret: str = ""
    origin_secret_header: str = "x-aab-origin"

    # Trust CF-Connecting-IP for the real client IP. Only honored once the
    # origin-secret check has passed, so a direct-to-origin caller can't spoof it.
    trust_cf_connecting_ip: bool = True

    # Cloudflare Access (Zero Trust) protects the admin/management plane. When
    # enabled, admin routes require BOTH a valid Access JWT (identity, verified
    # against the team's JWKS) AND an owner credential (session or admin token).
    cf_access_enabled: bool = False
    cf_access_team_domain: str = ""   # e.g. myteam.cloudflareaccess.com
    cf_access_aud: str = ""           # the Access application's AUD tag
    cf_access_allowed_emails: str = ""  # comma-separated; empty = any authenticated identity

    # Grace window (seconds) during which a rotated key's PREVIOUS secret still
    # authenticates, so rotation needs no coordinated cutover. Default 24h.
    key_rotation_grace_seconds: int = 86400

    # Escape hatch: allow public mode (origin_secret set) WITHOUT Cloudflare
    # Access on the admin plane. Off by default so a misconfigured deploy fails
    # closed at boot instead of silently guarding admin with the password alone.
    allow_insecure_admin: bool = False

    def public_mode(self) -> bool:
        """True once an edge origin secret is configured (internet exposure)."""
        return bool(self.origin_secret)


# Plugin services are discovered from env, keyed by SERVICE (one container may
# host several plugin ids): PLUGIN_URL_<SERVICE> + PLUGIN_TOKEN_<SERVICE>.
# Read straight from the environment because the set of services is open.
_PLUGIN_URL_PREFIX = "PLUGIN_URL_"
_PLUGIN_TOKEN_PREFIX = "PLUGIN_TOKEN_"


def plugin_services(environ: dict | None = None) -> dict[str, tuple[str, str]]:
    """{service: (base_url, token)} for every configured plugin service.

    A service with a URL but no token is skipped (and reported by the
    registry): talking to a plugin without its token would either fail or,
    worse, succeed against a plugin that forgot to require one.
    """
    env = os.environ if environ is None else environ
    out: dict[str, tuple[str, str]] = {}
    for name, url in env.items():
        if not name.startswith(_PLUGIN_URL_PREFIX) or not url.strip():
            continue
        service = name[len(_PLUGIN_URL_PREFIX):].lower()
        token = env.get(_PLUGIN_TOKEN_PREFIX + service.upper(), "")
        if service and token.strip():
            out[service] = (url.strip().rstrip("/"), token.strip())
    return dict(sorted(out.items()))


def validate_exposure(s: "Settings") -> None:
    """Fail closed at startup on unsafe internet-exposure configurations."""
    if s.cf_access_enabled and (not s.cf_access_team_domain or not s.cf_access_aud):
        raise RuntimeError(
            "CF_ACCESS_ENABLED requires CF_ACCESS_TEAM_DOMAIN and CF_ACCESS_AUD")
    if s.public_mode() and not s.cf_access_enabled and not s.allow_insecure_admin:
        raise RuntimeError(
            "Public mode (ORIGIN_SECRET set) leaves the admin plane on the owner "
            "password alone. Enable Cloudflare Access (CF_ACCESS_ENABLED=true, "
            "CF_ACCESS_TEAM_DOMAIN, CF_ACCESS_AUD) to protect it, or set "
            "ALLOW_INSECURE_ADMIN=true to override at your own risk.")


@lru_cache
def get_settings() -> Settings:
    """Cached accessor; tests clear the cache after tweaking env vars."""
    return Settings()
