"""Broker configuration, environment-first (12-factor: everything via env vars).

Only broker-wide settings live here. Per-plugin settings (sidecar URL, GitHub
App id, ...) are plugin config stored in the database and edited from the
console, so adding a plugin never touches this file.
"""

from functools import lru_cache

from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    # The broker's own database: principals, keys, grants, decisions, ledger.
    broker_db: str = "/gwdata/broker.db"

    # Host headers accepted on the /mcp endpoint (DNS-rebinding protection).
    # Comma-separated; ":*" allows any port. Extend when serving beyond localhost.
    mcp_allowed_hosts: str = "localhost:*,127.0.0.1:*"

    # --- Broker-owned secrets (generated by scripts/init_secrets.py) --------

    # One-time token that authorizes creating the owner account. Inert once
    # setup has completed (app_config.setup_completed), even if left in .env.
    setup_token: str | None = None
    # Fernet key encrypting plugin_secrets at rest (used only via crypto.py).
    broker_secrets_key: str | None = None
    # HMAC key for the hash-chained decision record.
    decision_signing_key: str | None = None

    # --- Owner sessions ------------------------------------------------------

    # Console login sessions die after this much inactivity (12h) or this long
    # after login regardless of activity (7d), whichever comes first.
    session_idle_seconds: int = 43200
    session_absolute_seconds: int = 604800

    # --- Authority -----------------------------------------------------------

    # How many delegation hops below a root key are allowed. Each hop can only
    # narrow, but deep chains are hard for a human to reason about.
    max_delegation_depth: int = 3

    # How often the scheduler looks for due queued actions.
    scheduler_tick_seconds: int = 15

    # --- Internet exposure (see deploy/DEPLOY.md) ---------------------------

    # Origin lockdown. When origin_secret is set, EVERY request must carry it in
    # origin_secret_header (injected by a Cloudflare Transform Rule), else 403.
    # This stops anyone who finds the origin IP from bypassing Cloudflare.
    origin_secret: str = ""
    origin_secret_header: str = "x-aab-origin"

    # Trust CF-Connecting-IP for the real client IP. Only honored once the
    # origin-secret check has passed, so a direct-to-origin caller can't spoof it.
    trust_cf_connecting_ip: bool = True

    # Cloudflare Access (Zero Trust) protects the admin/management plane. When
    # enabled, admin routes require BOTH a valid Access JWT (identity, verified
    # against the team's JWKS) AND an owner credential (session or admin token).
    cf_access_enabled: bool = False
    cf_access_team_domain: str = ""   # e.g. myteam.cloudflareaccess.com
    cf_access_aud: str = ""           # the Access application's AUD tag
    cf_access_allowed_emails: str = ""  # comma-separated; empty = any authenticated identity

    # Grace window (seconds) during which a rotated key's PREVIOUS secret still
    # authenticates, so rotation needs no coordinated cutover. Default 24h.
    key_rotation_grace_seconds: int = 86400

    # Escape hatch: allow public mode (origin_secret set) WITHOUT Cloudflare
    # Access on the admin plane. Off by default so a misconfigured deploy fails
    # closed at boot instead of silently guarding admin with the password alone.
    allow_insecure_admin: bool = False

    def public_mode(self) -> bool:
        """True once an edge origin secret is configured (internet exposure)."""
        return bool(self.origin_secret)


def validate_exposure(s: "Settings") -> None:
    """Fail closed at startup on unsafe internet-exposure configurations."""
    if s.cf_access_enabled and (not s.cf_access_team_domain or not s.cf_access_aud):
        raise RuntimeError(
            "CF_ACCESS_ENABLED requires CF_ACCESS_TEAM_DOMAIN and CF_ACCESS_AUD")
    if s.public_mode() and not s.cf_access_enabled and not s.allow_insecure_admin:
        raise RuntimeError(
            "Public mode (ORIGIN_SECRET set) leaves the admin plane on the owner "
            "password alone. Enable Cloudflare Access (CF_ACCESS_ENABLED=true, "
            "CF_ACCESS_TEAM_DOMAIN, CF_ACCESS_AUD) to protect it, or set "
            "ALLOW_INSECURE_ADMIN=true to override at your own risk.")


@lru_cache
def get_settings() -> Settings:
    """Cached accessor; tests clear the cache after tweaking env vars."""
    return Settings()
